version: 2
jobs:
  build:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
